Repository terasolunaorg/terasoluna-tourreservation-mybatis3, pull requests merged in 2019-01, with the labels that each got.

#245 correct wrong validation message #605
  terasoluna-tourreservation-web/src/main/resources/ValidationMessages_ja.properties
Labels: status: in-progress, version: 5.4.2

#243 [mybatis3/5.4.x] delete unnecessary file #600
  pom.xml.skrnew
Labels: status: in-progress, type: bug, version: 5.4.2

#246 fix build profile of terasoluna-gfw #602
  .travis.yml
Labels: status: in-progress, type: improvement, version: 5.5.1

#247 update selenium 3.14.0 + webdrivermanager 3.1.1 #571
  .travis.yml
  README.md
  pom.xml
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FirefoxDriverFactoryBean.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/WebDriverManagerFactoryBean.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterValidateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LanguageSwitchTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInReservUpdateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/SystemErrorTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TokenCheckErrorTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchPaginationTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchRegistValidateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnLogInTourSearchTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnauthorizedAccessTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/WaitWebDriverEventListener.java
  terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/selenium.properties
  terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
  terasoluna-tourreservation-selenium/src/test/resources/wdm.properties
Labels: status: in-progress, type: new-feature, version: 5.5.1
