Repository terasolunaorg/terasoluna-tourreservation-mybatis3, pull requests merged in 2019-03, with the labels that each got.

#249 update jdbc driver #612
  pom.xml
Labels: status: in-progress

#250 findOne -> findById delete -> deleteById #578
  terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/repository/age/AgeRepository.java
  terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/repository/customer/CustomerRepository.java
  terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepository.java
  terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/customer/CustomerServiceImpl.java
  terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/AuthorizedReserveSharedServiceImpl.java
  terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImpl.java
  terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/tourinfo/PriceCalculateSharedServiceImpl.java
  terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/userdetails/ReservationUserDetailsService.java
  terasoluna-tourreservation-domain/src/main/resources/org/terasoluna/tourreservation/domain/repository/age/AgeRepository.xml
  terasoluna-tourreservation-domain/src/main/resources/org/terasoluna/tourreservation/domain/repository/customer/CustomerRepository.xml
  terasoluna-tourreservation-domain/src/main/resources/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepository.xml
  terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/customer/CustomerServiceImplTest.java
  terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest.java
  terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java
Labels: status: in-progress

#252 [Spring 5.x] Dropped JasperReports support #582
  pom.xml
  terasoluna-tourreservation-domain/pom.xml
  terasoluna-tourreservation-web/pom.xml
  terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java
  terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ReservationReportPdfStamperView.java
  terasoluna-tourreservation-web/src/main/resources/META-INF/spring/application.properties
  terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
  terasoluna-tourreservation-web/src/main/resources/reports/reservationReport.pdf
  terasoluna-tourreservation-web/src/main/webapp/WEB-INF/reports/reservationReportPdf.jrxml
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ReservationReportPdfStamperViewTest.java
Labels: status: in-progress, type: new-feature, version: 5.5.1

#251 resolve deprecated api #614
  terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/customer/CustomerServiceImplTest.java
  terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/constants/MessageKeysGen.java
  terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourHelperTest.java
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/searchtour/SearchTourControllerTest.java
Labels: status: in-progress, type: improvement, version: 5.5.1
