Repository terasolunaorg/terasoluna-tourreservation-mybatis3, pull requests merged in 2019-04, with the labels that each got.

#253 [5.4.x] use UserDetails at ReserveTourControllerTest #584
  terasoluna-tourreservation-web/pom.xml
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourControllerTest.java
Labels: status: in-progress, type: bug, version: 5.4.2

#256 update to 5.6.0-SNAPSHOT #618
  pom.xml
  terasoluna-tourreservation-domain/pom.xml
  terasoluna-tourreservation-env/pom.xml
  terasoluna-tourreservation-initdb/pom.xml
  terasoluna-tourreservation-selenium/pom.xml
  terasoluna-tourreservation-web/pom.xml
Labels: status: in-progress

#255 update to 5.5.2-SNAPSHOT #618
  .travis.yml
  pom.xml
  terasoluna-tourreservation-domain/pom.xml
  terasoluna-tourreservation-env/pom.xml
  terasoluna-tourreservation-initdb/pom.xml
  terasoluna-tourreservation-selenium/pom.xml
  terasoluna-tourreservation-web/pom.xml
Labels: status: in-progress

#254 [5.4.x] resolve deprecated api #614
  terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/customer/CustomerServiceImplTest.java
  terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/constants/MessageKeysGen.java
  terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managecustomer/ManageCustomerControllerTest.java
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourHelperTest.java
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/searchtour/SearchTourControllerTest.java
Labels: status: in-progress, type: improvement, version: 5.4.2

#260 [5.4.x] replace schema location for Spring from http to https #624
  terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-codelist.xml
  terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-domain.xml
  terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-infra.xml
  terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/tourreservation-domain.xml
  terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/tourreservation-infra.xml
  terasoluna-tourreservation-domain/src/test/resources/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest-context.xml
  terasoluna-tourreservation-domain/src/test/resources/test-context.xml
  terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
  terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
  terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
  terasoluna-tourreservation-env/src/main/resources/META-INF/spring/terasoluna-tourreservation-env.xml
  terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
  terasoluna-tourreservation-web/src/main/resources/META-INF/spring/applicationContext.xml
  terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
  terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
Labels: status: in-progress

#259 udpate selenium backport #573
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FirefoxDriverFactoryBean.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterValidateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LanguageSwitchTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInReservUpdateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/SystemErrorTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TokenCheckErrorTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchPaginationTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchRegistValidateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnLogInTourSearchTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnauthorizedAccessTest.java
  terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
Labels: status: in-progress
